import type { Metadata } from "next";
import { Provider } from "@/components/ui/provider";
import "./globals.css";
import { ThemeProvider } from "next-themes";

export const metadata: Metadata = {
  title: "P2P dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <ThemeProvider attribute="class">
        <body>
          <Provider defaultTheme="light" attribute="class">
            {children}
          </Provider>
        </body>
      </ThemeProvider>
    </html>
  );
}
